#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Determines repo mode, ownership, and cross-project repo availability
# for the dump skill. Single injected check — no arguments.
#
# Resolution order for standards/knowledgebase:
#   1. ~/source/<name> (normal local dev)
#   2. ~/<name> (simpler home layout)
#   3. ./<name> (sandbox child repo)
#   3. NOT_FOUND
#
# Output (exit 0):
#
#   single-repo:
#     MODE: single
#     OWNERSHIP: APPLICABLE|NOT_APPLICABLE: <reason>
#     STANDARDS: <absolute-path>|NOT_FOUND
#     KNOWLEDGEBASE: <absolute-path>|NOT_FOUND
#
#   multi-repo:
#     MODE: multi
#     REPO: <name> APPLICABLE|NOT_APPLICABLE: <reason>
#     ...
#     STANDARDS: <absolute-path>|NOT_FOUND
#     KNOWLEDGEBASE: <absolute-path>|NOT_FOUND
#
#   no repo:
#     MODE: none

set -euo pipefail

check_owner() {
  local url="$1"
  url=${url%%/}
  local owner=${url%/*}
  owner=${owner##*[/:]}
  case "$owner" in
    jewzaam|nmalik) echo "APPLICABLE" ;;
    *) echo "NOT_APPLICABLE: origin owner '$owner' is not a user-owned repo" ;;
  esac
}

resolve_repo() {
  local name="$1"
  local candidate
  for candidate in "$HOME/source/$name" "$HOME/$name" "./$name"; do
    if git -C "$candidate" rev-parse --git-dir &>/dev/null; then
      echo "$(cd "$candidate" && pwd)"
      return
    fi
  done
  echo "NOT_FOUND"
}

# Try CWD as a git repo first
if url=$(git remote get-url origin 2>/dev/null); then
  echo "MODE: single"
  echo "OWNERSHIP: $(check_owner "$url")"
  echo "STANDARDS: $(resolve_repo standards)"
  echo "KNOWLEDGEBASE: $(resolve_repo knowledgebase)"
  exit 0
fi

# CWD is not a git repo — scan for child repos
repos=()
while IFS= read -r dir; do
  [ -n "$dir" ] && repos+=("$dir")
done < <(find . -mindepth 2 -maxdepth 2 -name .git -type d 2>/dev/null | sed 's|^\./||;s|/\.git$||' | sort)

if [ ${#repos[@]} -eq 0 ]; then
  echo "MODE: none"
  exit 0
fi

echo "MODE: multi"
for repo in "${repos[@]}"; do
  repo_url=$(git -C "$repo" remote get-url origin 2>/dev/null) || {
    echo "REPO: $repo NOT_APPLICABLE: no origin remote"
    continue
  }
  echo "REPO: $repo $(check_owner "$repo_url")"
done
echo "STANDARDS: $(resolve_repo standards)"
echo "KNOWLEDGEBASE: $(resolve_repo knowledgebase)"
