#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.7)
#
# Checks whether the current repo (cwd) is owned by the user. The dump
# skill uses this to gate writes to ~/source/standards/: standards are
# only updated from sessions running inside user-owned repos.
#
# Logic copied (not referenced) from the standards applicability check
# in the jewzaam-reviews repo. Kept minimal — only the ownership gate,
# no subdomain enumeration.
#
# Output (one line, exit 0):
#   APPLICABLE
#   NOT_APPLICABLE: <reason>

set -euo pipefail

url=$(git remote get-url origin 2>/dev/null) || { echo "NOT_APPLICABLE: no origin remote"; exit 0; }
url=${url%%/}
owner=${url%/*}
owner=${owner##*[/:]}

case "$owner" in
  jewzaam|nmalik) echo "APPLICABLE" ;;
  *) echo "NOT_APPLICABLE: origin owner '$owner' is not a user-owned repo" ;;
esac
