#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.7)
#
# Emits both the raw and HTTPS-converted origin remote URLs for the
# local repo (cwd), for ~/source/standards/, and for
# ~/source/knowledgebase/. The dump skill consumes this via ! injection
# at skill load so subagents do not have to convert SSH-form remotes
# themselves — determinism over inference.
#
# Output (exit 0):
#   LOCAL_REMOTE_RAW: <url|none>
#   LOCAL_REMOTE_HTTPS: <url|none>
#   STANDARDS_REMOTE_RAW: <url|none>
#   STANDARDS_REMOTE_HTTPS: <url|none>
#   KNOWLEDGEBASE_REMOTE_RAW: <url|none>
#   KNOWLEDGEBASE_REMOTE_HTTPS: <url|none>

set -euo pipefail

to_https() {
  local u="$1"
  [ -z "$u" ] && { echo "none"; return; }
  u="${u#git@}"
  u="${u/://}"
  u="${u%.git}"
  case "$u" in
    https://*) ;;
    http://*)  ;;
    *) u="https://$u" ;;
  esac
  echo "$u"
}

local_raw=$(git remote get-url origin 2>/dev/null || true)
standards_raw=$(git -C "$HOME/source/standards" remote get-url origin 2>/dev/null || true)
knowledgebase_raw=$(git -C "$HOME/source/knowledgebase" remote get-url origin 2>/dev/null || true)

echo "LOCAL_REMOTE_RAW: ${local_raw:-none}"
echo "LOCAL_REMOTE_HTTPS: $(to_https "$local_raw")"
echo "STANDARDS_REMOTE_RAW: ${standards_raw:-none}"
echo "STANDARDS_REMOTE_HTTPS: $(to_https "$standards_raw")"
echo "KNOWLEDGEBASE_REMOTE_RAW: ${knowledgebase_raw:-none}"
echo "KNOWLEDGEBASE_REMOTE_HTTPS: $(to_https "$knowledgebase_raw")"
