#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Emits both the raw and HTTPS-converted origin remote URLs for a
# repo, for standards, and for knowledgebase. The dump skill consumes
# this via ! injection at skill load so subagents do not have to
# convert SSH-form remotes themselves.
#
# Usage: get-remotes.sh [repo-dir]
#   repo-dir defaults to CWD. In multi-repo mode, called once per
#   child repo with that repo's path.
#
# Resolution order for standards/knowledgebase:
#   1. ~/source/<name> (normal local dev)
#   2. ~/<name> (simpler home layout)
#   3. ./<name> (sandbox child repo)
#
# Output (exit 0):
#   LOCAL_REMOTE_RAW: <url|none>
#   LOCAL_REMOTE_HTTPS: <url|none>
#   LOCAL_VISIBILITY: PUBLIC|PRIVATE|UNKNOWN
#   STANDARDS_REMOTE_RAW: <url|none>
#   STANDARDS_REMOTE_HTTPS: <url|none>
#   KNOWLEDGEBASE_REMOTE_RAW: <url|none>
#   KNOWLEDGEBASE_REMOTE_HTTPS: <url|none>

set -euo pipefail

repo_dir="${1:-.}"

to_https() {
  local u="$1"
  [ -z "$u" ] && { echo "none"; return; }
  u="${u#git@}"
  u="${u/://}"
  u="${u%.git}"
  case "$u" in
    https://*) ;;
    http://*)  ;;
    *) u="https://$u" ;;
  esac
  echo "$u"
}

# Visibility of the local repo, used to gate whether a doc written into a
# PUBLIC target (standards, knowledgebase) may cite the source repo by URL.
# Citing a private repo there produces a 404 for every outside reader.
#
# `git` cannot answer this — visibility is a forge concept, not a git one, and
# an anonymous `ls-remote` probe is defeated by any cached credential helper.
# `gh` is therefore required for a definitive answer.
#
# Degrades to UNKNOWN when gh is absent, unauthenticated, or the remote is not
# a GitHub repo. Callers must treat UNKNOWN as PRIVATE: a missing citation is
# recoverable, a published dead link is not.
detect_visibility() {
  local dir="$1"
  local out
  command -v gh >/dev/null 2>&1 || { echo "UNKNOWN"; return; }
  out=$( cd "$dir" 2>/dev/null && gh repo view --json isPrivate -q .isPrivate 2>/dev/null ) || true
  case "$out" in
    true)  echo "PRIVATE" ;;
    false) echo "PUBLIC" ;;
    *)     echo "UNKNOWN" ;;
  esac
}

resolve_repo() {
  local name="$1"
  local candidate
  for candidate in "$HOME/source/$name" "$HOME/$name" "./$name"; do
    if git -C "$candidate" rev-parse --git-dir &>/dev/null; then
      echo "$(cd "$candidate" && pwd)"
      return
    fi
  done
}

local_raw=$(git -C "$repo_dir" remote get-url origin 2>/dev/null || true)

standards_dir=$(resolve_repo standards)
knowledgebase_dir=$(resolve_repo knowledgebase)

standards_raw=$( [ -n "$standards_dir" ] && git -C "$standards_dir" remote get-url origin 2>/dev/null || true)
knowledgebase_raw=$( [ -n "$knowledgebase_dir" ] && git -C "$knowledgebase_dir" remote get-url origin 2>/dev/null || true)

echo "LOCAL_REMOTE_RAW: ${local_raw:-none}"
echo "LOCAL_REMOTE_HTTPS: $(to_https "$local_raw")"
echo "LOCAL_VISIBILITY: $(detect_visibility "$repo_dir")"
echo "STANDARDS_REMOTE_RAW: ${standards_raw:-none}"
echo "STANDARDS_REMOTE_HTTPS: $(to_https "$standards_raw")"
echo "KNOWLEDGEBASE_REMOTE_RAW: ${knowledgebase_raw:-none}"
echo "KNOWLEDGEBASE_REMOTE_HTTPS: $(to_https "$knowledgebase_raw")"
