#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Resolves a cross-project repo by name and prints its path + listing.
#
# Usage: resolve-listing.sh <name>
#   name: "standards" or "knowledgebase"
#
# Resolution order:
#   1. ~/source/<name>
#   2. ~/<name>
#   3. ./<name>
#
# Output (exit 0):
#   Found:
#     <name> path: <absolute-path>
#     <ls -la output>
#   Not found:
#     <name>: NOT_FOUND

set -euo pipefail

name="${1:?usage: resolve-listing.sh <name>}"

for d in "$HOME/source/$name" "$HOME/$name" "./$name"; do
  if git -C "$d" rev-parse --git-dir &>/dev/null; then
    resolved=$(cd "$d" && pwd)
    echo "$name path: $resolved"
    ls -la "$d/"
    exit 0
  fi
done

echo "$name: NOT_FOUND"
